# Build settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
title: "Grab a ☕️ ..."
title_separator: "-"
name: "Felipe Marino"
description: >-
  A blog about Swift development, learnings, iOS, server side, tips and tricks..
url: "https://marinofelipe.github.io"
atom_feed:
  path: "feed.xml"
repository: marinofelipe/marinofelipe.github.io

# Site Author
author:
  name: "Felipe Marino"
  avatar: "/assets/avatars/me.png"
  bio: "iOS Engineer, Swift Developer. Here I write findings and learnings about Swift, Xcode and more.."
  location: "Germany, Berlin"
  github: marinofelipe
  twitter: _marinofelipe

# Reading Files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      header:
        image: /assets/banners/tv_tower.png

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: "UA-165961290-1"
    anonymize_ip: true